import type { Component } from "vue";
import {
  Activity,
  AlertCircle,
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpDown,
  BookOpen,
  Bookmark,
  Bot,
  Box,
  Brain,
  Cable,
  Camera,
  Check,
  CheckCircle,
  CheckSquare,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleAlert,
  CircleCheck,
  CircleHelp,
  Clock,
  Coins,
  Compass,
  Copy,
  CornerDownLeft,
  Cpu,
  Database,
  Download,
  Drama,
  EllipsisVertical,
  Eye,
  FileJson,
  FileText,
  Filter,
  Flame,
  FolderOpen,
  Github,
  Globe,
  GripVertical,
  Hash,
  Home,
  ImagePlus,
  Info,
  Key,
  Languages,
  Layers,
  LayoutGrid,
  Link,
  List,
  Loader2,
  LoaderCircle,
  MapPin,
  Maximize2,
  MessageCircle,
  MessageSquarePlus,
  Moon,
  MoreHorizontal,
  Palette,
  Pencil,
  PenTool,
  Pin,
  Play,
  Plug,
  Plus,
  Power,
  Puzzle,
  Radio,
  RefreshCw,
  RotateCcw,
  Route,
  Save,
  Scale,
  ScrollText,
  Search,
  SearchX,
  Server,
  Settings,
  Settings2,
  SlidersHorizontal,
  Sparkles,
  Square,
  Star,
  Sun,
  Timer,
  ToggleLeft,
  Trash2,
  TriangleAlert,
  Type,
  Upload,
  User,
  UserCircle,
  X,
  Zap,
} from "lucide-vue-next";

/**
 * Registry of every Lucide icon referenced in the app, keyed by its kebab-case
 * name (the same names the codebase used with Nuxt UI's `i-lucide-*` convention).
 * `AppIcon` resolves against this map; adding a new icon = one import + one entry.
 */
export const icons: Record<string, Component> = {
  activity: Activity,
  "alert-circle": AlertCircle,
  "alert-triangle": AlertTriangle,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "arrow-up": ArrowUp,
  "arrow-up-down": ArrowUpDown,
  "book-open": BookOpen,
  bookmark: Bookmark,
  bot: Bot,
  box: Box,
  brain: Brain,
  cable: Cable,
  camera: Camera,
  check: Check,
  "check-circle": CheckCircle,
  "check-square": CheckSquare,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "circle-alert": CircleAlert,
  "circle-check": CircleCheck,
  clock: Clock,
  coins: Coins,
  compass: Compass,
  copy: Copy,
  "corner-down-left": CornerDownLeft,
  cpu: Cpu,
  database: Database,
  download: Download,
  drama: Drama,
  "ellipsis-vertical": EllipsisVertical,
  eye: Eye,
  "file-json": FileJson,
  "file-text": FileText,
  filter: Filter,
  flame: Flame,
  "folder-open": FolderOpen,
  github: Github,
  globe: Globe,
  "grip-vertical": GripVertical,
  hash: Hash,
  home: Home,
  "image-plus": ImagePlus,
  info: Info,
  key: Key,
  languages: Languages,
  layers: Layers,
  "layout-grid": LayoutGrid,
  link: Link,
  list: List,
  "loader-2": Loader2,
  "loader-circle": LoaderCircle,
  "map-pin": MapPin,
  "maximize-2": Maximize2,
  "message-circle": MessageCircle,
  "message-square-plus": MessageSquarePlus,
  moon: Moon,
  "more-horizontal": MoreHorizontal,
  palette: Palette,
  pencil: Pencil,
  "pen-tool": PenTool,
  pin: Pin,
  play: Play,
  plug: Plug,
  plus: Plus,
  power: Power,
  puzzle: Puzzle,
  radio: Radio,
  "refresh-cw": RefreshCw,
  "rotate-ccw": RotateCcw,
  route: Route,
  save: Save,
  scale: Scale,
  "scroll-text": ScrollText,
  search: Search,
  "search-x": SearchX,
  server: Server,
  settings: Settings,
  "settings-2": Settings2,
  "sliders-horizontal": SlidersHorizontal,
  sparkles: Sparkles,
  square: Square,
  star: Star,
  sun: Sun,
  timer: Timer,
  "toggle-left": ToggleLeft,
  "trash-2": Trash2,
  "triangle-alert": TriangleAlert,
  type: Type,
  upload: Upload,
  user: User,
  "user-circle": UserCircle,
  x: X,
  zap: Zap,
};

/** Rendered when a name isn't found in the registry. */
export const fallbackIcon: Component = CircleHelp;
