<script setup lang="ts">
// Full-sentence reply candidates (autogenerated by the model). Rendered as
// stacked tappable cards rather than pills — they're whole lines the user sends,
// not short labels, so they need room to breathe.
defineProps<{
  items: string[];
  disabled?: boolean;
}>();

const emit = defineEmits<{
  select: [text: string];
}>();
</script>

<template>
  <div class="flex w-full max-w-xl flex-col gap-1.5">
    <button
      v-for="(text, i) in items"
      :key="i"
      :disabled="disabled"
      class="group flex w-full animate-fade-in-up items-start gap-2 rounded-lg border bg-card/60 px-3 py-2 text-left text-sm text-foreground transition-all duration-200 hover:border-primary/40 hover:bg-accent hover:shadow-[0_0_12px_var(--color-primary)/0.12] disabled:cursor-not-allowed disabled:opacity-50"
      :style="{ animationDelay: `${i * 60}ms` }"
      @click="emit('select', text)"
    >
      <AppIcon
        name="i-lucide-corner-down-left"
        class="mt-0.5 size-3.5 shrink-0 text-muted-foreground transition-colors group-hover:text-primary"
      />
      <span class="min-w-0">{{ text }}</span>
    </button>
  </div>
</template>
