"""add_chat_is_bookmarked

Revision ID: 71042953805b
Revises: fa2d23a42928
Create Date: 2026-07-04 18:55:51.296090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71042953805b'
down_revision = 'fa2d23a42928'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('is_bookmarked', sa.Boolean(), server_default='false', nullable=False, comment='Whether the chat session is bookmarked'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'is_bookmarked')
    # ### end Alembic commands ###
