"""consolidated schema

Revision ID: a40885deaf32
Revises: 
Create Date: 2026-06-04 16:20:55.698206

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy.vector

# revision identifiers, used by Alembic.
revision = 'a40885deaf32'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # VectorChord (and its pgvector dependency, pulled in via CASCADE) must exist
    # before the embeddings.embedding vector(768) column and the vchordrq index.
    op.execute("CREATE EXTENSION IF NOT EXISTS vchord CASCADE")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('name', sa.String(length=100), nullable=False, comment='Display name of the character'),
    sa.Column('description', sa.Text(), nullable=True, comment='Brief description or tagline for the character'),
    sa.Column('personality', sa.Text(), nullable=True, comment="Detailed description of the character's traits and behavior"),
    sa.Column('first_message', sa.Text(), nullable=True, comment='Initial message the character sends when starting a new chat'),
    sa.Column('example_dialogues', sa.JSON().with_variant(postgresql.ARRAY(sa.String()), 'postgresql'), nullable=True, comment='List of example exchanges to guide roleplay style'),
    sa.Column('avatar', sa.String(length=255), nullable=True, comment='Path to the original avatar image file'),
    sa.Column('avatar_thumbnail', sa.String(length=255), nullable=True, comment='Path to the generated avatar thumbnail image'),
    sa.Column('scenario', sa.Text(), nullable=True, comment='Current scenario/situation for RP context'),
    sa.Column('post_history_instructions', sa.Text(), nullable=True, comment='Jailbreak/instructions inserted after chat history'),
    sa.Column('alternate_greetings', sa.JSON().with_variant(postgresql.ARRAY(sa.String()), 'postgresql'), nullable=True, comment='Alternative first messages'),
    sa.Column('tags', sa.JSON().with_variant(postgresql.ARRAY(sa.String()), 'postgresql'), nullable=True, comment='Tags for categorizing and filtering characters'),
    sa.Column('gender', sa.Enum('male', 'female', 'non-binary', 'others', name='gender'), nullable=True, comment="Character's gender"),
    sa.Column('custom_gender', sa.String(length=100), nullable=True, comment="Custom gender value when gender is set to 'others'"),
    sa.Column('creator', sa.String(length=100), nullable=True, comment='Creator or author of the character card'),
    sa.Column('system_prompt', sa.Text(), nullable=True, comment='Per-character system prompt override (V2 spec)'),
    sa.Column('creator_notes', sa.Text(), nullable=True, comment="Creator's notes about the character (not sent to LLM)"),
    sa.Column('character_version', sa.String(length=100), nullable=True, comment='Semantic version string from card spec'),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False, comment='Character card version'),
    sa.Column('id', sa.String(length=12), nullable=False, comment='Unique short identifier (12 characters)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the record was created (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the record was last updated (UTC)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('embeddings',
    sa.Column('source_type', sa.String(length=20), nullable=False, comment='Source: message, data_bank'),
    sa.Column('source_id', sa.String(length=12), nullable=False, comment='ID of the source entity'),
    sa.Column('content_hash', sa.BigInteger(), nullable=False, comment='Hash for dedup'),
    sa.Column('content', sa.Text(), nullable=False, comment='Original text chunk'),
    sa.Column('chunk_index', sa.Integer(), nullable=False, comment='Position within chunked source'),
    sa.Column('model_name', sa.String(length=100), nullable=False, comment='Embedding model that produced this vector'),
    sa.Column('dimensions', sa.Integer(), nullable=False, comment='Vector dimensions'),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=False),
    sa.Column('id', sa.String(length=12), nullable=False, comment='Unique short identifier (12 characters)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the record was created (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the record was last updated (UTC)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_embeddings_content_hash'), 'embeddings', ['content_hash'], unique=False)
    op.create_index(op.f('ix_embeddings_source_id'), 'embeddings', ['source_id'], unique=False)
    op.create_index(op.f('ix_embeddings_source_type'), 'embeddings', ['source_type'], unique=False)
    # VectorChord approximate-NN index backing the cosine `<=>` similarity search.
    # `lists` is omitted (flat RaBitQ scan) — the right default for modest local datasets.
    op.execute(
        "CREATE INDEX ix_embeddings_vchordrq ON embeddings "
        "USING vchordrq (embedding vector_cosine_ops) "
        "WITH (options = $$\nresidual_quantization = true\n$$)"
    )
    op.create_table('error_logs',
    sa.Column('error_type', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('stack_trace', sa.Text(), nullable=True),
    sa.Column('context', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.String(length=12), nullable=False, comment='Unique short identifier (12 characters)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the record was created (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the record was last updated (UTC)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_error_logs_type_created', 'error_logs', ['error_type', 'created_at'], unique=False)
    op.create_table('http_logs',
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('path', sa.String(length=2048), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('client_ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('request_body', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('response_body', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.String(length=12), nullable=False, comment='Unique short identifier (12 characters)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the record was created (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the record was last updated (UTC)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_http_logs_created', 'http_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_http_logs_request_id'), 'http_logs', ['request_id'], unique=False)
    op.create_table('model_families',
    sa.Column('name', sa.String(length=100), nullable=False, comment='Display name of the model family'),
    sa.Column('family_identifier', sa.String(length=100), nullable=False, comment='URL-safe identifier following provider/model-name pattern'),
    sa.Column('description', sa.Text(), nullable=True, comment='Detailed description of the model family capabilities'),
    sa.Column('provider_types', sa.JSON().with_variant(postgresql.ARRAY(sa.String()), 'postgresql'), nullable=False, comment='List of provider types that support this family'),
    sa.Column('parameters', sa.JSON(), nullable=False, comment='Schema and default values for supported parameters'),
    sa.Column('unsupported_parameters', sa.JSON().with_variant(postgresql.ARRAY(sa.String()), 'postgresql'), nullable=False, comment='List of parameters explicitly known to be unsupported by this family'),
    sa.Column('extra_metadata', sa.JSON(), nullable=True, comment='Additional family-specific technical metadata'),
    sa.Column('id', sa.String(length=12), nullable=False, comment='Unique short identifier (12 characters)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the record was created (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the record was last updated (UTC)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_model_families_family_identifier'), 'model_families', ['family_identifier'], unique=True)
    op.create_table('personas',
    sa.Column('name', sa.String(length=100), nullable=False, comment='Unique name of the user persona'),
    sa.Column('description', sa.Text(), nullable=True, comment="Detailed description of the user's role or characteristics"),
    sa.Column('is_default', sa.Boolean(), nullable=False, comment='Whether this persona is automatically selected for new chats'),
    sa.Column('avatar', sa.String(length=255), nullable=True, comment='Path to the user persona avatar image'),
    sa.Column('avatar_thumbnail', sa.String(length=255), nullable=True, comment='Path to the user persona avatar thumbnail'),
    sa.Column('id', sa.String(length=12), nullable=False, comment='Unique short identifier (12 characters)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the record was created (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the record was last updated (UTC)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personas_name'), 'personas', ['name'], unique=True)
    op.create_table('presets',
    sa.Column('name', sa.String(length=100), nullable=False, comment='Display name of the preset'),
    sa.Column('description', sa.Text(), nullable=True, comment="Brief description of the preset's purpose"),
    sa.Column('parameters', sa.JSON(), nullable=False, comment='Sampling parameter overrides (temperature, top_p, etc.)'),
    sa.Column('is_default', sa.Boolean(), nullable=False, comment='Whether this preset is the default'),
    sa.Column('id', sa.String(length=12), nullable=False, comment='Unique short identifier (12 characters)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the record was created (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the record was last updated (UTC)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_presets_name'), 'presets', ['name'], unique=True)
    op.create_table('prompt_fragments',
    sa.Column('name', sa.String(length=100), nullable=False, comment='Display name'),
    sa.Column('description', sa.Text(), nullable=True, comment="Brief description of the fragment's purpose"),
    sa.Column('fragment_type', sa.String(length=50), nullable=False, comment='Category: system, nsfw, jailbreak, instruction, context'),
    sa.Column('content', sa.Text(), nullable=False, comment='Jinja2 template text for this fragment'),
    sa.Column('is_global', sa.Boolean(), nullable=False, comment='Available to all templates if True'),
    sa.Column('id', sa.String(length=12), nullable=False, comment='Unique short identifier (12 characters)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the record was created (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the record was last updated (UTC)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_fragments_name'), 'prompt_fragments', ['name'], unique=True)
    op.create_table('prompt_templates',
    sa.Column('name', sa.String(length=100), nullable=False, comment='Unique name of the prompt template'),
    sa.Column('description', sa.Text(), nullable=True, comment="Brief description of the template's purpose"),
    sa.Column('is_default', sa.Boolean(), nullable=False, comment='Whether this template is automatically selected for new chats'),
    sa.Column('system_template', sa.Text(), nullable=False, comment='Jinja2 template string for the system prompt'),
    sa.Column('component_order', sa.JSON(), nullable=False, comment='Ordered list of component names for prompt construction'),
    sa.Column('components_enabled', sa.JSON(), nullable=False, comment='Map of component names to their enabled status'),
    sa.Column('max_history_tokens', sa.Integer(), nullable=True, comment='Maximum number of tokens to include from chat history'),
    sa.Column('id', sa.String(length=12), nullable=False, comment='Unique short identifier (12 characters)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the record was created (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the record was last updated (UTC)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_templates_name'), 'prompt_templates', ['name'], unique=True)
    op.create_table('providers',
    sa.Column('name', sa.String(length=100), nullable=False, comment='Unique name of the AI provider'),
    sa.Column('base_url', sa.String(length=255), nullable=True, comment='API endpoint base URL for the service'),
    sa.Column('api_key_env_var', sa.String(length=100), nullable=True, comment='Name of the environment variable storing the API key'),
    sa.Column('provider_type', sa.Enum('xai', 'google', 'openai', 'anthropic', 'openrouter', 'ollama', 'custom', name='providertype'), nullable=False, comment='Classification of the provider (openai, anthropic, etc.)'),
    sa.Column('enabled', sa.Boolean(), nullable=False, comment='Whether this provider is currently active and usable'),
    sa.Column('id', sa.String(length=12), nullable=False, comment='Unique short identifier (12 characters)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the record was created (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the record was last updated (UTC)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('lorebooks',
    sa.Column('name', sa.String(length=200), nullable=False, comment='Display name'),
    sa.Column('description', sa.Text(), nullable=True, comment='Optional description'),
    sa.Column('is_global', sa.Boolean(), nullable=False, comment='Applies to all chats globally'),
    sa.Column('character_id', sa.String(length=12), nullable=True, comment='Owning character'),
    sa.Column('id', sa.String(length=12), nullable=False, comment='Unique short identifier (12 characters)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the record was created (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the record was last updated (UTC)'),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('models',
    sa.Column('provider_id', sa.String(length=12), nullable=False, comment='Unique identifier of the AI provider for this model'),
    sa.Column('model_identifier', sa.String(length=100), nullable=False, comment="Provider-specific model name (e.g., 'gpt-4o-mini', 'claude-4.5-sonnet')"),
    sa.Column('openrouter_identifier', sa.String(length=100), nullable=True, comment="OpenRouter model identifier (e.g., 'openai/gpt-4o', 'sao10k/l3-euryale-70b')"),
    sa.Column('use_openrouter', sa.Boolean(), nullable=False, comment='If True, route through OpenRouter'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Display name of the model'),
    sa.Column('model_family_id', sa.String(length=12), nullable=False, comment='Unique identifier of the model family this model belongs to'),
    sa.Column('template_id', sa.String(length=12), nullable=True, comment='Default prompt template for this model configuration'),
    sa.Column('parameters', sa.JSON(), nullable=False, comment='Model-specific overrides for sampling and generation parameters'),
    sa.Column('enabled', sa.Boolean(), nullable=False, comment='Whether this model is currently available for use'),
    sa.Column('id', sa.String(length=12), nullable=False, comment='Unique short identifier (12 characters)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the record was created (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the record was last updated (UTC)'),
    sa.ForeignKeyConstraint(['model_family_id'], ['model_families.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['template_id'], ['prompt_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_models_model_family_id'), 'models', ['model_family_id'], unique=False)
    op.create_index(op.f('ix_models_model_identifier'), 'models', ['model_identifier'], unique=False)
    op.create_index(op.f('ix_models_openrouter_identifier'), 'models', ['openrouter_identifier'], unique=False)
    op.create_index(op.f('ix_models_provider_id'), 'models', ['provider_id'], unique=False)
    op.create_index(op.f('ix_models_template_id'), 'models', ['template_id'], unique=False)
    op.create_index(op.f('ix_models_use_openrouter'), 'models', ['use_openrouter'], unique=False)
    op.create_table('template_fragments',
    sa.Column('template_id', sa.String(length=12), nullable=False),
    sa.Column('fragment_id', sa.String(length=12), nullable=False),
    sa.Column('position', sa.String(length=50), nullable=False, comment='Injection position: after_system, pre_history, post_history'),
    sa.Column('ordinal', sa.Integer(), nullable=False, comment='Order within position (0-based)'),
    sa.Column('id', sa.String(length=12), nullable=False, comment='Unique short identifier (12 characters)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the record was created (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the record was last updated (UTC)'),
    sa.ForeignKeyConstraint(['fragment_id'], ['prompt_fragments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['prompt_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_template_fragments_fragment_id'), 'template_fragments', ['fragment_id'], unique=False)
    op.create_index(op.f('ix_template_fragments_template_id'), 'template_fragments', ['template_id'], unique=False)
    op.create_table('chats',
    sa.Column('character_id', sa.String(length=12), nullable=False, comment='Unique identifier of the character being roleplayed'),
    sa.Column('model_id', sa.String(length=12), nullable=True, comment='Unique identifier of the LLM model used for this chat'),
    sa.Column('title', sa.String(length=200), nullable=True, comment='User-defined or auto-generated title for the conversation'),
    sa.Column('preview', sa.Text(), nullable=True, comment='Short text snippet of the last message for list display'),
    sa.Column('model_name', sa.String(length=100), nullable=True, comment='Snapshot of the model name used (persists even if model is deleted)'),
    sa.Column('template_id', sa.String(length=12), nullable=True, comment='Prompt template (uses default if None)'),
    sa.Column('persona_id', sa.String(length=12), nullable=True, comment='User persona (uses default if None)'),
    sa.Column('preset_id', sa.String(length=12), nullable=True, comment='Parameter preset (uses model defaults if None)'),
    sa.Column('id', sa.String(length=12), nullable=False, comment='Unique short identifier (12 characters)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the record was created (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the record was last updated (UTC)'),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['preset_id'], ['presets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['prompt_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chats_character_id'), 'chats', ['character_id'], unique=False)
    op.create_index(op.f('ix_chats_model_id'), 'chats', ['model_id'], unique=False)
    op.create_index(op.f('ix_chats_persona_id'), 'chats', ['persona_id'], unique=False)
    op.create_index(op.f('ix_chats_preset_id'), 'chats', ['preset_id'], unique=False)
    op.create_index(op.f('ix_chats_template_id'), 'chats', ['template_id'], unique=False)
    op.create_table('lore_entries',
    sa.Column('lorebook_id', sa.String(length=12), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False, comment='Display name / memo'),
    sa.Column('content', sa.Text(), nullable=False, comment='Lore text injected into prompt'),
    sa.Column('keys', sa.JSON().with_variant(postgresql.ARRAY(sa.String()), 'postgresql'), nullable=False, comment='Primary trigger keywords'),
    sa.Column('secondary_keys', sa.JSON().with_variant(postgresql.ARRAY(sa.String()), 'postgresql'), nullable=False, comment='Secondary filter keywords'),
    sa.Column('secondary_logic', sa.Enum('and_any', 'and_all', 'not_any', 'not_all', name='secondarylogic'), nullable=False, comment='Logic for secondary keyword matching'),
    sa.Column('case_sensitive', sa.Boolean(), nullable=False),
    sa.Column('match_whole_words', sa.Boolean(), nullable=False),
    sa.Column('use_regex', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('constant', sa.Boolean(), nullable=False, comment='Always active, ignores keywords'),
    sa.Column('position', sa.Enum('before_character', 'after_character', 'at_depth', 'before_examples', name='insertionposition'), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False, comment='Message depth for AT_DEPTH position'),
    sa.Column('role', sa.Enum('user', 'assistant', 'system', name='messagerole'), nullable=False, comment='Message role for AT_DEPTH insertion'),
    sa.Column('priority', sa.Integer(), nullable=False, comment='Higher = inserted first'),
    sa.Column('scan_depth', sa.Integer(), nullable=True, comment='Per-entry scan depth override'),
    sa.Column('ignore_budget', sa.Boolean(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=12), nullable=False, comment='Unique short identifier (12 characters)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the record was created (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the record was last updated (UTC)'),
    sa.ForeignKeyConstraint(['lorebook_id'], ['lorebooks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_bank_entries',
    sa.Column('name', sa.String(length=200), nullable=False, comment='Display name'),
    sa.Column('content', sa.Text(), nullable=False, comment='Knowledge text'),
    sa.Column('scope', sa.String(length=20), nullable=False, comment='Scope: global, character, chat'),
    sa.Column('character_id', sa.String(length=12), nullable=True, comment='For character-scoped entries'),
    sa.Column('chat_id', sa.String(length=12), nullable=True, comment='For chat-scoped entries'),
    sa.Column('id', sa.String(length=12), nullable=False, comment='Unique short identifier (12 characters)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the record was created (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the record was last updated (UTC)'),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_bank_entries_character_id'), 'data_bank_entries', ['character_id'], unique=False)
    op.create_index(op.f('ix_data_bank_entries_chat_id'), 'data_bank_entries', ['chat_id'], unique=False)
    op.create_index(op.f('ix_data_bank_entries_scope'), 'data_bank_entries', ['scope'], unique=False)
    op.create_table('llm_audit_logs',
    sa.Column('chat_id', sa.String(length=12), nullable=True, comment='Chat this call belongs to (null if the chat was deleted)'),
    sa.Column('provider', sa.String(length=50), nullable=False, comment='Provider type (e.g. openai, anthropic)'),
    sa.Column('model', sa.String(length=255), nullable=False, comment='Model identifier sent to the provider'),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False, comment='success or an error classification'),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('request_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False, comment='Raw request messages sent to the provider'),
    sa.Column('response_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True, comment='Raw response (content, reasoning, finish_reason, usage)'),
    sa.Column('id', sa.String(length=12), nullable=False, comment='Unique short identifier (12 characters)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the record was created (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the record was last updated (UTC)'),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_llm_audit_logs_chat_created', 'llm_audit_logs', ['chat_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_llm_audit_logs_chat_id'), 'llm_audit_logs', ['chat_id'], unique=False)
    op.create_table('messages',
    sa.Column('chat_id', sa.String(length=12), nullable=False, comment='Unique identifier of the chat this message belongs to'),
    sa.Column('role', sa.Enum('user', 'assistant', 'system', name='messagerole'), nullable=False, comment='Role of the message sender (user, assistant, system)'),
    sa.Column('content', sa.Text(), nullable=False, comment='Full text content of the message'),
    sa.Column('token_count', sa.Integer(), nullable=True, comment='Cached token count for this message'),
    sa.Column('reasoning_content', sa.Text(), nullable=True, comment='Reasoning/thinking content from the model'),
    sa.Column('active_index', sa.Integer(), nullable=False, comment='Index of the currently active alternative (0 = original)'),
    sa.Column('id', sa.String(length=12), nullable=False, comment='Unique short identifier (12 characters)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the record was created (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the record was last updated (UTC)'),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_chat_id'), 'messages', ['chat_id'], unique=False)
    op.create_table('message_alternatives',
    sa.Column('message_id', sa.String(length=12), nullable=False, comment='Parent message this alternative belongs to'),
    sa.Column('content', sa.Text(), nullable=False, comment='Alternative response text'),
    sa.Column('token_count', sa.Integer(), nullable=True, comment='Cached token count'),
    sa.Column('ordinal', sa.Integer(), nullable=False, comment='Position in the alternatives list (0-based)'),
    sa.Column('id', sa.String(length=12), nullable=False, comment='Unique short identifier (12 characters)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the record was created (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the record was last updated (UTC)'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_alternatives_message_id'), 'message_alternatives', ['message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_alternatives_message_id'), table_name='message_alternatives')
    op.drop_table('message_alternatives')
    op.drop_index(op.f('ix_messages_chat_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_llm_audit_logs_chat_id'), table_name='llm_audit_logs')
    op.drop_index('ix_llm_audit_logs_chat_created', table_name='llm_audit_logs')
    op.drop_table('llm_audit_logs')
    op.drop_index(op.f('ix_data_bank_entries_scope'), table_name='data_bank_entries')
    op.drop_index(op.f('ix_data_bank_entries_chat_id'), table_name='data_bank_entries')
    op.drop_index(op.f('ix_data_bank_entries_character_id'), table_name='data_bank_entries')
    op.drop_table('data_bank_entries')
    op.drop_table('lore_entries')
    op.drop_index(op.f('ix_chats_template_id'), table_name='chats')
    op.drop_index(op.f('ix_chats_preset_id'), table_name='chats')
    op.drop_index(op.f('ix_chats_persona_id'), table_name='chats')
    op.drop_index(op.f('ix_chats_model_id'), table_name='chats')
    op.drop_index(op.f('ix_chats_character_id'), table_name='chats')
    op.drop_table('chats')
    op.drop_index(op.f('ix_template_fragments_template_id'), table_name='template_fragments')
    op.drop_index(op.f('ix_template_fragments_fragment_id'), table_name='template_fragments')
    op.drop_table('template_fragments')
    op.drop_index(op.f('ix_models_use_openrouter'), table_name='models')
    op.drop_index(op.f('ix_models_template_id'), table_name='models')
    op.drop_index(op.f('ix_models_provider_id'), table_name='models')
    op.drop_index(op.f('ix_models_openrouter_identifier'), table_name='models')
    op.drop_index(op.f('ix_models_model_identifier'), table_name='models')
    op.drop_index(op.f('ix_models_model_family_id'), table_name='models')
    op.drop_table('models')
    op.drop_table('lorebooks')
    op.drop_table('providers')
    op.drop_index(op.f('ix_prompt_templates_name'), table_name='prompt_templates')
    op.drop_table('prompt_templates')
    op.drop_index(op.f('ix_prompt_fragments_name'), table_name='prompt_fragments')
    op.drop_table('prompt_fragments')
    op.drop_index(op.f('ix_presets_name'), table_name='presets')
    op.drop_table('presets')
    op.drop_index(op.f('ix_personas_name'), table_name='personas')
    op.drop_table('personas')
    op.drop_index(op.f('ix_model_families_family_identifier'), table_name='model_families')
    op.drop_table('model_families')
    op.drop_index(op.f('ix_http_logs_request_id'), table_name='http_logs')
    op.drop_index('ix_http_logs_created', table_name='http_logs')
    op.drop_table('http_logs')
    op.drop_index('ix_error_logs_type_created', table_name='error_logs')
    op.drop_table('error_logs')
    op.drop_index(op.f('ix_embeddings_source_type'), table_name='embeddings')
    op.drop_index(op.f('ix_embeddings_source_id'), table_name='embeddings')
    op.drop_index(op.f('ix_embeddings_content_hash'), table_name='embeddings')
    op.drop_table('embeddings')
    op.drop_table('characters')
    # PostgreSQL enum types are not dropped automatically when their tables are.
    for enum_name in ("gender", "providertype", "secondarylogic", "insertionposition", "messagerole"):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
