"""reconcile schema drift with models

Revision ID: a5cfbeb7d0d2
Revises: d39bb8a9cb5c
Create Date: 2026-06-03 22:05:04.433861

"""
import pgvector.sqlalchemy.vector
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a5cfbeb7d0d2'
down_revision = 'd39bb8a9cb5c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('characters', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='Display name of the character',
               existing_nullable=False)
    op.alter_column('characters', 'description',
               existing_type=sa.TEXT(),
               comment='Brief description or tagline for the character',
               existing_nullable=True)
    op.alter_column('characters', 'personality',
               existing_type=sa.TEXT(),
               comment="Detailed description of the character's traits and behavior",
               existing_nullable=True)
    op.alter_column('characters', 'first_message',
               existing_type=sa.TEXT(),
               comment='Initial message the character sends when starting a new chat',
               existing_nullable=True)
    op.alter_column('characters', 'example_dialogues',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               comment='List of example exchanges to guide roleplay style',
               existing_nullable=True)
    op.alter_column('characters', 'avatar',
               existing_type=sa.VARCHAR(length=255),
               comment='Path to the original avatar image file',
               existing_nullable=True)
    op.alter_column('characters', 'avatar_thumbnail',
               existing_type=sa.VARCHAR(length=255),
               comment='Path to the generated avatar thumbnail image',
               existing_nullable=True)
    op.alter_column('characters', 'scenario',
               existing_type=sa.TEXT(),
               comment='Current scenario/situation for RP context',
               existing_nullable=True)
    op.alter_column('characters', 'post_history_instructions',
               existing_type=sa.TEXT(),
               comment='Jailbreak/instructions inserted after chat history',
               existing_nullable=True)
    op.alter_column('characters', 'alternate_greetings',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               comment='Alternative first messages',
               existing_nullable=True)
    op.alter_column('characters', 'tags',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               comment='Tags for categorizing and filtering characters',
               existing_nullable=True)
    op.alter_column('characters', 'gender',
               existing_type=postgresql.ENUM('male', 'female', 'non_binary', 'others', name='gender'),
               comment="Character's gender",
               existing_nullable=True)
    op.alter_column('characters', 'custom_gender',
               existing_type=sa.VARCHAR(length=100),
               comment="Custom gender value when gender is set to 'others'",
               existing_nullable=True)
    op.alter_column('characters', 'creator',
               existing_type=sa.VARCHAR(length=100),
               comment='Creator or author of the character card',
               existing_nullable=True)
    op.alter_column('characters', 'system_prompt',
               existing_type=sa.TEXT(),
               comment='Per-character system prompt override (V2 spec)',
               existing_nullable=True)
    op.alter_column('characters', 'creator_notes',
               existing_type=sa.TEXT(),
               comment="Creator's notes about the character (not sent to LLM)",
               existing_nullable=True)
    op.alter_column('characters', 'character_version',
               existing_type=sa.VARCHAR(length=100),
               comment='Semantic version string from card spec',
               existing_nullable=True)
    op.alter_column('characters', 'version',
               existing_type=sa.INTEGER(),
               comment='Character card version',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('characters', 'id',
               existing_type=sa.VARCHAR(length=12),
               comment='Unique short identifier (12 characters)',
               existing_nullable=False)
    op.alter_column('characters', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when the record was created (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('characters', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when the record was last updated (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('chats', 'character_id',
               existing_type=sa.VARCHAR(length=12),
               comment='Unique identifier of the character being roleplayed',
               existing_nullable=False)
    op.alter_column('chats', 'model_id',
               existing_type=sa.VARCHAR(length=12),
               comment='Unique identifier of the LLM model used for this chat',
               existing_nullable=True)
    op.alter_column('chats', 'title',
               existing_type=sa.VARCHAR(length=200),
               comment='User-defined or auto-generated title for the conversation',
               existing_nullable=True)
    op.alter_column('chats', 'preview',
               existing_type=sa.TEXT(),
               comment='Short text snippet of the last message for list display',
               existing_nullable=True)
    op.alter_column('chats', 'model_name',
               existing_type=sa.VARCHAR(length=100),
               comment='Snapshot of the model name used (persists even if model is deleted)',
               existing_nullable=True)
    op.alter_column('chats', 'template_id',
               existing_type=sa.VARCHAR(length=12),
               comment='Prompt template (uses default if None)',
               existing_nullable=True)
    op.alter_column('chats', 'persona_id',
               existing_type=sa.VARCHAR(length=12),
               comment='User persona (uses default if None)',
               existing_nullable=True)
    op.alter_column('chats', 'preset_id',
               existing_type=sa.VARCHAR(length=12),
               comment='Parameter preset (uses model defaults if None)',
               existing_nullable=True)
    op.alter_column('chats', 'id',
               existing_type=sa.VARCHAR(length=12),
               comment='Unique short identifier (12 characters)',
               existing_nullable=False)
    op.alter_column('chats', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when the record was created (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('chats', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when the record was last updated (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('data_bank_entries', 'name',
               existing_type=sa.VARCHAR(length=200),
               comment='Display name',
               existing_nullable=False)
    op.alter_column('data_bank_entries', 'content',
               existing_type=sa.TEXT(),
               comment='Knowledge text',
               existing_nullable=False)
    op.alter_column('data_bank_entries', 'scope',
               existing_type=sa.VARCHAR(length=20),
               comment='Scope: global, character, chat',
               existing_nullable=False,
               existing_server_default=sa.text("'global'::character varying"))
    op.alter_column('data_bank_entries', 'character_id',
               existing_type=sa.VARCHAR(length=12),
               comment='For character-scoped entries',
               existing_nullable=True)
    op.alter_column('data_bank_entries', 'chat_id',
               existing_type=sa.VARCHAR(length=12),
               comment='For chat-scoped entries',
               existing_nullable=True)
    op.alter_column('data_bank_entries', 'id',
               existing_type=sa.VARCHAR(length=12),
               comment='Unique short identifier (12 characters)',
               existing_nullable=False)
    op.alter_column('data_bank_entries', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when the record was created (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('data_bank_entries', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when the record was last updated (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('embeddings', 'source_type',
               existing_type=sa.VARCHAR(length=20),
               comment='Source: message, data_bank',
               existing_nullable=False)
    op.alter_column('embeddings', 'source_id',
               existing_type=sa.VARCHAR(length=12),
               comment='ID of the source entity',
               existing_nullable=False)
    op.alter_column('embeddings', 'content_hash',
               existing_type=sa.BIGINT(),
               comment='Hash for dedup',
               existing_nullable=False)
    op.alter_column('embeddings', 'content',
               existing_type=sa.TEXT(),
               comment='Original text chunk',
               existing_nullable=False)
    op.alter_column('embeddings', 'chunk_index',
               existing_type=sa.INTEGER(),
               comment='Position within chunked source',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('embeddings', 'model_name',
               existing_type=sa.VARCHAR(length=100),
               comment='Embedding model that produced this vector',
               existing_nullable=False)
    op.alter_column('embeddings', 'dimensions',
               existing_type=sa.INTEGER(),
               comment='Vector dimensions',
               existing_nullable=False)
    op.alter_column('embeddings', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(),
               nullable=False)
    op.alter_column('embeddings', 'id',
               existing_type=sa.VARCHAR(length=12),
               comment='Unique short identifier (12 characters)',
               existing_nullable=False)
    op.alter_column('embeddings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when the record was created (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('embeddings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when the record was last updated (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('lore_entries', 'name',
               existing_type=sa.VARCHAR(length=200),
               comment='Display name / memo',
               existing_nullable=False)
    op.alter_column('lore_entries', 'content',
               existing_type=sa.TEXT(),
               comment='Lore text injected into prompt',
               existing_nullable=False)
    op.alter_column('lore_entries', 'keys',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               comment='Primary trigger keywords',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::character varying[]"))
    op.alter_column('lore_entries', 'secondary_keys',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               comment='Secondary filter keywords',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::character varying[]"))
    op.alter_column('lore_entries', 'secondary_logic',
               existing_type=postgresql.ENUM('and_any', 'and_all', 'not_any', 'not_all', name='secondarylogic'),
               comment='Logic for secondary keyword matching',
               existing_nullable=False,
               existing_server_default=sa.text("'and_any'::secondarylogic"))
    op.alter_column('lore_entries', 'constant',
               existing_type=sa.BOOLEAN(),
               comment='Always active, ignores keywords',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('lore_entries', 'depth',
               existing_type=sa.INTEGER(),
               comment='Message depth for AT_DEPTH position',
               existing_nullable=False,
               existing_server_default=sa.text('4'))
    op.alter_column('lore_entries', 'role',
               existing_type=postgresql.ENUM('user', 'assistant', 'system', name='messagerole'),
               comment='Message role for AT_DEPTH insertion',
               existing_nullable=False,
               existing_server_default=sa.text("'system'::messagerole"))
    op.alter_column('lore_entries', 'priority',
               existing_type=sa.INTEGER(),
               comment='Higher = inserted first',
               existing_nullable=False,
               existing_server_default=sa.text('100'))
    op.alter_column('lore_entries', 'scan_depth',
               existing_type=sa.INTEGER(),
               comment='Per-entry scan depth override',
               existing_nullable=True)
    op.alter_column('lore_entries', 'id',
               existing_type=sa.VARCHAR(length=12),
               comment='Unique short identifier (12 characters)',
               existing_nullable=False)
    op.alter_column('lore_entries', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when the record was created (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('lore_entries', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when the record was last updated (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('lorebooks', 'name',
               existing_type=sa.VARCHAR(length=200),
               comment='Display name',
               existing_nullable=False)
    op.alter_column('lorebooks', 'description',
               existing_type=sa.TEXT(),
               comment='Optional description',
               existing_nullable=True)
    op.alter_column('lorebooks', 'is_global',
               existing_type=sa.BOOLEAN(),
               comment='Applies to all chats globally',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('lorebooks', 'character_id',
               existing_type=sa.VARCHAR(length=12),
               comment='Owning character',
               existing_nullable=True)
    op.alter_column('lorebooks', 'id',
               existing_type=sa.VARCHAR(length=12),
               comment='Unique short identifier (12 characters)',
               existing_nullable=False)
    op.alter_column('lorebooks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when the record was created (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('lorebooks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when the record was last updated (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('message_alternatives', 'message_id',
               existing_type=sa.VARCHAR(length=12),
               comment='Parent message this alternative belongs to',
               existing_nullable=False)
    op.alter_column('message_alternatives', 'content',
               existing_type=sa.TEXT(),
               comment='Alternative response text',
               existing_nullable=False)
    op.alter_column('message_alternatives', 'token_count',
               existing_type=sa.INTEGER(),
               comment='Cached token count',
               existing_nullable=True)
    op.alter_column('message_alternatives', 'ordinal',
               existing_type=sa.INTEGER(),
               comment='Position in the alternatives list (0-based)',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('message_alternatives', 'id',
               existing_type=sa.VARCHAR(length=12),
               comment='Unique short identifier (12 characters)',
               existing_nullable=False)
    op.alter_column('message_alternatives', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when the record was created (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('message_alternatives', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when the record was last updated (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('messages', 'chat_id',
               existing_type=sa.VARCHAR(length=12),
               comment='Unique identifier of the chat this message belongs to',
               existing_nullable=False)
    op.alter_column('messages', 'role',
               existing_type=postgresql.ENUM('user', 'assistant', 'system', name='messagerole'),
               comment='Role of the message sender (user, assistant, system)',
               existing_nullable=False)
    op.alter_column('messages', 'content',
               existing_type=sa.TEXT(),
               comment='Full text content of the message',
               existing_nullable=False)
    op.alter_column('messages', 'token_count',
               existing_type=sa.INTEGER(),
               comment='Cached token count for this message',
               existing_nullable=True)
    op.alter_column('messages', 'reasoning_content',
               existing_type=sa.TEXT(),
               comment='Reasoning/thinking content from the model',
               existing_nullable=True)
    op.alter_column('messages', 'active_index',
               existing_type=sa.INTEGER(),
               comment='Index of the currently active alternative (0 = original)',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('messages', 'id',
               existing_type=sa.VARCHAR(length=12),
               comment='Unique short identifier (12 characters)',
               existing_nullable=False)
    op.alter_column('messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when the record was created (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('messages', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when the record was last updated (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('model_families', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='Display name of the model family',
               existing_nullable=False)
    op.alter_column('model_families', 'family_identifier',
               existing_type=sa.VARCHAR(length=100),
               comment='URL-safe identifier following provider/model-name pattern',
               existing_nullable=False)
    op.alter_column('model_families', 'description',
               existing_type=sa.TEXT(),
               comment='Detailed description of the model family capabilities',
               existing_nullable=True)
    op.alter_column('model_families', 'provider_types',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               comment='List of provider types that support this family',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::character varying[]"))
    op.alter_column('model_families', 'parameters',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Schema and default values for supported parameters',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::json"))
    op.alter_column('model_families', 'unsupported_parameters',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               comment='List of parameters explicitly known to be unsupported by this family',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::character varying[]"))
    op.alter_column('model_families', 'extra_metadata',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Additional family-specific technical metadata',
               existing_nullable=True)
    op.alter_column('model_families', 'id',
               existing_type=sa.VARCHAR(length=12),
               comment='Unique short identifier (12 characters)',
               existing_nullable=False)
    op.alter_column('model_families', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when the record was created (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('model_families', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when the record was last updated (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('model_families_family_identifier_key'), 'model_families', type_='unique')
    op.drop_index(op.f('ix_model_families_family_identifier'), table_name='model_families')
    op.create_index(op.f('ix_model_families_family_identifier'), 'model_families', ['family_identifier'], unique=True)
    op.alter_column('models', 'provider_id',
               existing_type=sa.VARCHAR(length=12),
               comment='Unique identifier of the AI provider for this model',
               existing_nullable=False)
    op.alter_column('models', 'model_identifier',
               existing_type=sa.VARCHAR(length=100),
               comment="Provider-specific model name (e.g., 'gpt-4o-mini', 'claude-4.5-sonnet')",
               existing_nullable=False)
    op.alter_column('models', 'openrouter_identifier',
               existing_type=sa.VARCHAR(length=100),
               comment="OpenRouter model identifier (e.g., 'openai/gpt-4o', 'sao10k/l3-euryale-70b')",
               existing_nullable=True)
    op.alter_column('models', 'use_openrouter',
               existing_type=sa.BOOLEAN(),
               comment='If True, route through OpenRouter',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('models', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='Display name of the model',
               existing_nullable=False)
    op.alter_column('models', 'model_family_id',
               existing_type=sa.VARCHAR(length=12),
               comment='Unique identifier of the model family this model belongs to',
               existing_nullable=False)
    op.alter_column('models', 'template_id',
               existing_type=sa.VARCHAR(length=12),
               comment='Default prompt template for this model configuration',
               existing_nullable=True)
    op.alter_column('models', 'parameters',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Model-specific overrides for sampling and generation parameters',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::json"))
    op.alter_column('models', 'enabled',
               existing_type=sa.BOOLEAN(),
               comment='Whether this model is currently available for use',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('models', 'id',
               existing_type=sa.VARCHAR(length=12),
               comment='Unique short identifier (12 characters)',
               existing_nullable=False)
    op.alter_column('models', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when the record was created (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('models', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when the record was last updated (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_models_openrouter_identifier'), 'models', ['openrouter_identifier'], unique=False)
    op.create_index(op.f('ix_models_use_openrouter'), 'models', ['use_openrouter'], unique=False)
    op.alter_column('personas', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='Unique name of the user persona',
               existing_nullable=False)
    op.alter_column('personas', 'description',
               existing_type=sa.TEXT(),
               comment="Detailed description of the user's role or characteristics",
               existing_nullable=True)
    op.alter_column('personas', 'is_default',
               existing_type=sa.BOOLEAN(),
               comment='Whether this persona is automatically selected for new chats',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('personas', 'avatar',
               existing_type=sa.VARCHAR(length=255),
               comment='Path to the user persona avatar image',
               existing_nullable=True)
    op.alter_column('personas', 'avatar_thumbnail',
               existing_type=sa.VARCHAR(length=255),
               comment='Path to the user persona avatar thumbnail',
               existing_nullable=True)
    op.alter_column('personas', 'id',
               existing_type=sa.VARCHAR(length=12),
               comment='Unique short identifier (12 characters)',
               existing_nullable=False)
    op.alter_column('personas', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when the record was created (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('personas', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when the record was last updated (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('personas_name_key'), 'personas', type_='unique')
    op.drop_index(op.f('ix_personas_name'), table_name='personas')
    op.create_index(op.f('ix_personas_name'), 'personas', ['name'], unique=True)
    op.alter_column('presets', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='Display name of the preset',
               existing_nullable=False)
    op.alter_column('presets', 'description',
               existing_type=sa.TEXT(),
               comment="Brief description of the preset's purpose",
               existing_nullable=True)
    op.alter_column('presets', 'parameters',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Sampling parameter overrides (temperature, top_p, etc.)',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::json"))
    op.alter_column('presets', 'is_default',
               existing_type=sa.BOOLEAN(),
               comment='Whether this preset is the default',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('presets', 'id',
               existing_type=sa.VARCHAR(length=12),
               comment='Unique short identifier (12 characters)',
               existing_nullable=False)
    op.alter_column('presets', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when the record was created (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('presets', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when the record was last updated (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('presets_name_key'), 'presets', type_='unique')
    op.drop_index(op.f('ix_presets_name'), table_name='presets')
    op.create_index(op.f('ix_presets_name'), 'presets', ['name'], unique=True)
    op.alter_column('prompt_fragments', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='Display name',
               existing_nullable=False)
    op.alter_column('prompt_fragments', 'description',
               existing_type=sa.TEXT(),
               comment="Brief description of the fragment's purpose",
               existing_nullable=True)
    op.alter_column('prompt_fragments', 'fragment_type',
               existing_type=sa.VARCHAR(length=50),
               comment='Category: system, nsfw, jailbreak, instruction, context',
               existing_nullable=False,
               existing_server_default=sa.text("'instruction'::character varying"))
    op.alter_column('prompt_fragments', 'content',
               existing_type=sa.TEXT(),
               comment='Jinja2 template text for this fragment',
               existing_nullable=False)
    op.alter_column('prompt_fragments', 'is_global',
               existing_type=sa.BOOLEAN(),
               comment='Available to all templates if True',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('prompt_fragments', 'id',
               existing_type=sa.VARCHAR(length=12),
               comment='Unique short identifier (12 characters)',
               existing_nullable=False)
    op.alter_column('prompt_fragments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when the record was created (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('prompt_fragments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when the record was last updated (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('prompt_fragments_name_key'), 'prompt_fragments', type_='unique')
    op.drop_index(op.f('ix_prompt_fragments_name'), table_name='prompt_fragments')
    op.create_index(op.f('ix_prompt_fragments_name'), 'prompt_fragments', ['name'], unique=True)
    op.alter_column('prompt_templates', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='Unique name of the prompt template',
               existing_nullable=False)
    op.alter_column('prompt_templates', 'description',
               existing_type=sa.TEXT(),
               comment="Brief description of the template's purpose",
               existing_nullable=True)
    op.alter_column('prompt_templates', 'is_default',
               existing_type=sa.BOOLEAN(),
               comment='Whether this template is automatically selected for new chats',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('prompt_templates', 'system_template',
               existing_type=sa.TEXT(),
               comment='Jinja2 template string for the system prompt',
               existing_nullable=False)
    op.alter_column('prompt_templates', 'component_order',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Ordered list of component names for prompt construction',
               existing_nullable=False)
    op.alter_column('prompt_templates', 'components_enabled',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Map of component names to their enabled status',
               existing_nullable=False)
    op.alter_column('prompt_templates', 'max_history_tokens',
               existing_type=sa.INTEGER(),
               comment='Maximum number of tokens to include from chat history',
               existing_nullable=True)
    op.alter_column('prompt_templates', 'id',
               existing_type=sa.VARCHAR(length=12),
               comment='Unique short identifier (12 characters)',
               existing_nullable=False)
    op.alter_column('prompt_templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when the record was created (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('prompt_templates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when the record was last updated (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('prompt_templates_name_key'), 'prompt_templates', type_='unique')
    op.drop_index(op.f('ix_prompt_templates_name'), table_name='prompt_templates')
    op.create_index(op.f('ix_prompt_templates_name'), 'prompt_templates', ['name'], unique=True)
    op.alter_column('providers', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='Unique name of the AI provider',
               existing_nullable=False)
    op.alter_column('providers', 'base_url',
               existing_type=sa.VARCHAR(length=255),
               comment='API endpoint base URL for the service',
               existing_nullable=True)
    op.alter_column('providers', 'api_key_env_var',
               existing_type=sa.VARCHAR(length=100),
               comment='Name of the environment variable storing the API key',
               existing_nullable=True)
    op.alter_column('providers', 'provider_type',
               existing_type=postgresql.ENUM('xai', 'google', 'openai', 'anthropic', 'openrouter', 'ollama', 'custom', name='providertype'),
               comment='Classification of the provider (openai, anthropic, etc.)',
               existing_nullable=False)
    op.alter_column('providers', 'enabled',
               existing_type=sa.BOOLEAN(),
               comment='Whether this provider is currently active and usable',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('providers', 'id',
               existing_type=sa.VARCHAR(length=12),
               comment='Unique short identifier (12 characters)',
               existing_nullable=False)
    op.alter_column('providers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when the record was created (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('providers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when the record was last updated (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('template_fragments', 'position',
               existing_type=sa.VARCHAR(length=50),
               comment='Injection position: after_system, pre_history, post_history',
               existing_nullable=False,
               existing_server_default=sa.text("'after_system'::character varying"))
    op.alter_column('template_fragments', 'ordinal',
               existing_type=sa.INTEGER(),
               comment='Order within position (0-based)',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('template_fragments', 'id',
               existing_type=sa.VARCHAR(length=12),
               comment='Unique short identifier (12 characters)',
               existing_nullable=False)
    op.alter_column('template_fragments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when the record was created (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('template_fragments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when the record was last updated (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('template_fragments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when the record was last updated (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('template_fragments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when the record was created (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('template_fragments', 'id',
               existing_type=sa.VARCHAR(length=12),
               comment=None,
               existing_comment='Unique short identifier (12 characters)',
               existing_nullable=False)
    op.alter_column('template_fragments', 'ordinal',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Order within position (0-based)',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('template_fragments', 'position',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Injection position: after_system, pre_history, post_history',
               existing_nullable=False,
               existing_server_default=sa.text("'after_system'::character varying"))
    op.alter_column('providers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when the record was last updated (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('providers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when the record was created (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('providers', 'id',
               existing_type=sa.VARCHAR(length=12),
               comment=None,
               existing_comment='Unique short identifier (12 characters)',
               existing_nullable=False)
    op.alter_column('providers', 'enabled',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Whether this provider is currently active and usable',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('providers', 'provider_type',
               existing_type=postgresql.ENUM('xai', 'google', 'openai', 'anthropic', 'openrouter', 'ollama', 'custom', name='providertype'),
               comment=None,
               existing_comment='Classification of the provider (openai, anthropic, etc.)',
               existing_nullable=False)
    op.alter_column('providers', 'api_key_env_var',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Name of the environment variable storing the API key',
               existing_nullable=True)
    op.alter_column('providers', 'base_url',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='API endpoint base URL for the service',
               existing_nullable=True)
    op.alter_column('providers', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Unique name of the AI provider',
               existing_nullable=False)
    op.drop_index(op.f('ix_prompt_templates_name'), table_name='prompt_templates')
    op.create_index(op.f('ix_prompt_templates_name'), 'prompt_templates', ['name'], unique=False)
    op.create_unique_constraint(op.f('prompt_templates_name_key'), 'prompt_templates', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('prompt_templates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when the record was last updated (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('prompt_templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when the record was created (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('prompt_templates', 'id',
               existing_type=sa.VARCHAR(length=12),
               comment=None,
               existing_comment='Unique short identifier (12 characters)',
               existing_nullable=False)
    op.alter_column('prompt_templates', 'max_history_tokens',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Maximum number of tokens to include from chat history',
               existing_nullable=True)
    op.alter_column('prompt_templates', 'components_enabled',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='Map of component names to their enabled status',
               existing_nullable=False)
    op.alter_column('prompt_templates', 'component_order',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='Ordered list of component names for prompt construction',
               existing_nullable=False)
    op.alter_column('prompt_templates', 'system_template',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Jinja2 template string for the system prompt',
               existing_nullable=False)
    op.alter_column('prompt_templates', 'is_default',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Whether this template is automatically selected for new chats',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('prompt_templates', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment="Brief description of the template's purpose",
               existing_nullable=True)
    op.alter_column('prompt_templates', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Unique name of the prompt template',
               existing_nullable=False)
    op.drop_index(op.f('ix_prompt_fragments_name'), table_name='prompt_fragments')
    op.create_index(op.f('ix_prompt_fragments_name'), 'prompt_fragments', ['name'], unique=False)
    op.create_unique_constraint(op.f('prompt_fragments_name_key'), 'prompt_fragments', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('prompt_fragments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when the record was last updated (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('prompt_fragments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when the record was created (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('prompt_fragments', 'id',
               existing_type=sa.VARCHAR(length=12),
               comment=None,
               existing_comment='Unique short identifier (12 characters)',
               existing_nullable=False)
    op.alter_column('prompt_fragments', 'is_global',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Available to all templates if True',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('prompt_fragments', 'content',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Jinja2 template text for this fragment',
               existing_nullable=False)
    op.alter_column('prompt_fragments', 'fragment_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Category: system, nsfw, jailbreak, instruction, context',
               existing_nullable=False,
               existing_server_default=sa.text("'instruction'::character varying"))
    op.alter_column('prompt_fragments', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment="Brief description of the fragment's purpose",
               existing_nullable=True)
    op.alter_column('prompt_fragments', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Display name',
               existing_nullable=False)
    op.drop_index(op.f('ix_presets_name'), table_name='presets')
    op.create_index(op.f('ix_presets_name'), 'presets', ['name'], unique=False)
    op.create_unique_constraint(op.f('presets_name_key'), 'presets', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('presets', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when the record was last updated (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('presets', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when the record was created (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('presets', 'id',
               existing_type=sa.VARCHAR(length=12),
               comment=None,
               existing_comment='Unique short identifier (12 characters)',
               existing_nullable=False)
    op.alter_column('presets', 'is_default',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Whether this preset is the default',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('presets', 'parameters',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='Sampling parameter overrides (temperature, top_p, etc.)',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::json"))
    op.alter_column('presets', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment="Brief description of the preset's purpose",
               existing_nullable=True)
    op.alter_column('presets', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Display name of the preset',
               existing_nullable=False)
    op.drop_index(op.f('ix_personas_name'), table_name='personas')
    op.create_index(op.f('ix_personas_name'), 'personas', ['name'], unique=False)
    op.create_unique_constraint(op.f('personas_name_key'), 'personas', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('personas', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when the record was last updated (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('personas', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when the record was created (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('personas', 'id',
               existing_type=sa.VARCHAR(length=12),
               comment=None,
               existing_comment='Unique short identifier (12 characters)',
               existing_nullable=False)
    op.alter_column('personas', 'avatar_thumbnail',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Path to the user persona avatar thumbnail',
               existing_nullable=True)
    op.alter_column('personas', 'avatar',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Path to the user persona avatar image',
               existing_nullable=True)
    op.alter_column('personas', 'is_default',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Whether this persona is automatically selected for new chats',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('personas', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment="Detailed description of the user's role or characteristics",
               existing_nullable=True)
    op.alter_column('personas', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Unique name of the user persona',
               existing_nullable=False)
    op.drop_index(op.f('ix_models_use_openrouter'), table_name='models')
    op.drop_index(op.f('ix_models_openrouter_identifier'), table_name='models')
    op.alter_column('models', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when the record was last updated (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('models', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when the record was created (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('models', 'id',
               existing_type=sa.VARCHAR(length=12),
               comment=None,
               existing_comment='Unique short identifier (12 characters)',
               existing_nullable=False)
    op.alter_column('models', 'enabled',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Whether this model is currently available for use',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('models', 'parameters',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='Model-specific overrides for sampling and generation parameters',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::json"))
    op.alter_column('models', 'template_id',
               existing_type=sa.VARCHAR(length=12),
               comment=None,
               existing_comment='Default prompt template for this model configuration',
               existing_nullable=True)
    op.alter_column('models', 'model_family_id',
               existing_type=sa.VARCHAR(length=12),
               comment=None,
               existing_comment='Unique identifier of the model family this model belongs to',
               existing_nullable=False)
    op.alter_column('models', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Display name of the model',
               existing_nullable=False)
    op.alter_column('models', 'use_openrouter',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='If True, route through OpenRouter',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('models', 'openrouter_identifier',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment="OpenRouter model identifier (e.g., 'openai/gpt-4o', 'sao10k/l3-euryale-70b')",
               existing_nullable=True)
    op.alter_column('models', 'model_identifier',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment="Provider-specific model name (e.g., 'gpt-4o-mini', 'claude-4.5-sonnet')",
               existing_nullable=False)
    op.alter_column('models', 'provider_id',
               existing_type=sa.VARCHAR(length=12),
               comment=None,
               existing_comment='Unique identifier of the AI provider for this model',
               existing_nullable=False)
    op.drop_index(op.f('ix_model_families_family_identifier'), table_name='model_families')
    op.create_index(op.f('ix_model_families_family_identifier'), 'model_families', ['family_identifier'], unique=False)
    op.create_unique_constraint(op.f('model_families_family_identifier_key'), 'model_families', ['family_identifier'], postgresql_nulls_not_distinct=False)
    op.alter_column('model_families', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when the record was last updated (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('model_families', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when the record was created (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('model_families', 'id',
               existing_type=sa.VARCHAR(length=12),
               comment=None,
               existing_comment='Unique short identifier (12 characters)',
               existing_nullable=False)
    op.alter_column('model_families', 'extra_metadata',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='Additional family-specific technical metadata',
               existing_nullable=True)
    op.alter_column('model_families', 'unsupported_parameters',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               comment=None,
               existing_comment='List of parameters explicitly known to be unsupported by this family',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::character varying[]"))
    op.alter_column('model_families', 'parameters',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='Schema and default values for supported parameters',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::json"))
    op.alter_column('model_families', 'provider_types',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               comment=None,
               existing_comment='List of provider types that support this family',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::character varying[]"))
    op.alter_column('model_families', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Detailed description of the model family capabilities',
               existing_nullable=True)
    op.alter_column('model_families', 'family_identifier',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='URL-safe identifier following provider/model-name pattern',
               existing_nullable=False)
    op.alter_column('model_families', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Display name of the model family',
               existing_nullable=False)
    op.alter_column('messages', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when the record was last updated (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when the record was created (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('messages', 'id',
               existing_type=sa.VARCHAR(length=12),
               comment=None,
               existing_comment='Unique short identifier (12 characters)',
               existing_nullable=False)
    op.alter_column('messages', 'active_index',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Index of the currently active alternative (0 = original)',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('messages', 'reasoning_content',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Reasoning/thinking content from the model',
               existing_nullable=True)
    op.alter_column('messages', 'token_count',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Cached token count for this message',
               existing_nullable=True)
    op.alter_column('messages', 'content',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Full text content of the message',
               existing_nullable=False)
    op.alter_column('messages', 'role',
               existing_type=postgresql.ENUM('user', 'assistant', 'system', name='messagerole'),
               comment=None,
               existing_comment='Role of the message sender (user, assistant, system)',
               existing_nullable=False)
    op.alter_column('messages', 'chat_id',
               existing_type=sa.VARCHAR(length=12),
               comment=None,
               existing_comment='Unique identifier of the chat this message belongs to',
               existing_nullable=False)
    op.alter_column('message_alternatives', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when the record was last updated (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('message_alternatives', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when the record was created (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('message_alternatives', 'id',
               existing_type=sa.VARCHAR(length=12),
               comment=None,
               existing_comment='Unique short identifier (12 characters)',
               existing_nullable=False)
    op.alter_column('message_alternatives', 'ordinal',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Position in the alternatives list (0-based)',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('message_alternatives', 'token_count',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Cached token count',
               existing_nullable=True)
    op.alter_column('message_alternatives', 'content',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Alternative response text',
               existing_nullable=False)
    op.alter_column('message_alternatives', 'message_id',
               existing_type=sa.VARCHAR(length=12),
               comment=None,
               existing_comment='Parent message this alternative belongs to',
               existing_nullable=False)
    op.alter_column('lorebooks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when the record was last updated (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('lorebooks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when the record was created (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('lorebooks', 'id',
               existing_type=sa.VARCHAR(length=12),
               comment=None,
               existing_comment='Unique short identifier (12 characters)',
               existing_nullable=False)
    op.alter_column('lorebooks', 'character_id',
               existing_type=sa.VARCHAR(length=12),
               comment=None,
               existing_comment='Owning character',
               existing_nullable=True)
    op.alter_column('lorebooks', 'is_global',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Applies to all chats globally',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('lorebooks', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Optional description',
               existing_nullable=True)
    op.alter_column('lorebooks', 'name',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='Display name',
               existing_nullable=False)
    op.alter_column('lore_entries', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when the record was last updated (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('lore_entries', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when the record was created (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('lore_entries', 'id',
               existing_type=sa.VARCHAR(length=12),
               comment=None,
               existing_comment='Unique short identifier (12 characters)',
               existing_nullable=False)
    op.alter_column('lore_entries', 'scan_depth',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Per-entry scan depth override',
               existing_nullable=True)
    op.alter_column('lore_entries', 'priority',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Higher = inserted first',
               existing_nullable=False,
               existing_server_default=sa.text('100'))
    op.alter_column('lore_entries', 'role',
               existing_type=postgresql.ENUM('user', 'assistant', 'system', name='messagerole'),
               comment=None,
               existing_comment='Message role for AT_DEPTH insertion',
               existing_nullable=False,
               existing_server_default=sa.text("'system'::messagerole"))
    op.alter_column('lore_entries', 'depth',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Message depth for AT_DEPTH position',
               existing_nullable=False,
               existing_server_default=sa.text('4'))
    op.alter_column('lore_entries', 'constant',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Always active, ignores keywords',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('lore_entries', 'secondary_logic',
               existing_type=postgresql.ENUM('and_any', 'and_all', 'not_any', 'not_all', name='secondarylogic'),
               comment=None,
               existing_comment='Logic for secondary keyword matching',
               existing_nullable=False,
               existing_server_default=sa.text("'and_any'::secondarylogic"))
    op.alter_column('lore_entries', 'secondary_keys',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               comment=None,
               existing_comment='Secondary filter keywords',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::character varying[]"))
    op.alter_column('lore_entries', 'keys',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               comment=None,
               existing_comment='Primary trigger keywords',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::character varying[]"))
    op.alter_column('lore_entries', 'content',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Lore text injected into prompt',
               existing_nullable=False)
    op.alter_column('lore_entries', 'name',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='Display name / memo',
               existing_nullable=False)
    op.alter_column('embeddings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when the record was last updated (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('embeddings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when the record was created (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('embeddings', 'id',
               existing_type=sa.VARCHAR(length=12),
               comment=None,
               existing_comment='Unique short identifier (12 characters)',
               existing_nullable=False)
    op.alter_column('embeddings', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(),
               nullable=True)
    op.alter_column('embeddings', 'dimensions',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Vector dimensions',
               existing_nullable=False)
    op.alter_column('embeddings', 'model_name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Embedding model that produced this vector',
               existing_nullable=False)
    op.alter_column('embeddings', 'chunk_index',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Position within chunked source',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('embeddings', 'content',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Original text chunk',
               existing_nullable=False)
    op.alter_column('embeddings', 'content_hash',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='Hash for dedup',
               existing_nullable=False)
    op.alter_column('embeddings', 'source_id',
               existing_type=sa.VARCHAR(length=12),
               comment=None,
               existing_comment='ID of the source entity',
               existing_nullable=False)
    op.alter_column('embeddings', 'source_type',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Source: message, data_bank',
               existing_nullable=False)
    op.alter_column('data_bank_entries', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when the record was last updated (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('data_bank_entries', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when the record was created (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('data_bank_entries', 'id',
               existing_type=sa.VARCHAR(length=12),
               comment=None,
               existing_comment='Unique short identifier (12 characters)',
               existing_nullable=False)
    op.alter_column('data_bank_entries', 'chat_id',
               existing_type=sa.VARCHAR(length=12),
               comment=None,
               existing_comment='For chat-scoped entries',
               existing_nullable=True)
    op.alter_column('data_bank_entries', 'character_id',
               existing_type=sa.VARCHAR(length=12),
               comment=None,
               existing_comment='For character-scoped entries',
               existing_nullable=True)
    op.alter_column('data_bank_entries', 'scope',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Scope: global, character, chat',
               existing_nullable=False,
               existing_server_default=sa.text("'global'::character varying"))
    op.alter_column('data_bank_entries', 'content',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Knowledge text',
               existing_nullable=False)
    op.alter_column('data_bank_entries', 'name',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='Display name',
               existing_nullable=False)
    op.alter_column('chats', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when the record was last updated (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('chats', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when the record was created (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('chats', 'id',
               existing_type=sa.VARCHAR(length=12),
               comment=None,
               existing_comment='Unique short identifier (12 characters)',
               existing_nullable=False)
    op.alter_column('chats', 'preset_id',
               existing_type=sa.VARCHAR(length=12),
               comment=None,
               existing_comment='Parameter preset (uses model defaults if None)',
               existing_nullable=True)
    op.alter_column('chats', 'persona_id',
               existing_type=sa.VARCHAR(length=12),
               comment=None,
               existing_comment='User persona (uses default if None)',
               existing_nullable=True)
    op.alter_column('chats', 'template_id',
               existing_type=sa.VARCHAR(length=12),
               comment=None,
               existing_comment='Prompt template (uses default if None)',
               existing_nullable=True)
    op.alter_column('chats', 'model_name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Snapshot of the model name used (persists even if model is deleted)',
               existing_nullable=True)
    op.alter_column('chats', 'preview',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Short text snippet of the last message for list display',
               existing_nullable=True)
    op.alter_column('chats', 'title',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='User-defined or auto-generated title for the conversation',
               existing_nullable=True)
    op.alter_column('chats', 'model_id',
               existing_type=sa.VARCHAR(length=12),
               comment=None,
               existing_comment='Unique identifier of the LLM model used for this chat',
               existing_nullable=True)
    op.alter_column('chats', 'character_id',
               existing_type=sa.VARCHAR(length=12),
               comment=None,
               existing_comment='Unique identifier of the character being roleplayed',
               existing_nullable=False)
    op.alter_column('characters', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when the record was last updated (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('characters', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when the record was created (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('characters', 'id',
               existing_type=sa.VARCHAR(length=12),
               comment=None,
               existing_comment='Unique short identifier (12 characters)',
               existing_nullable=False)
    op.alter_column('characters', 'version',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Character card version',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('characters', 'character_version',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Semantic version string from card spec',
               existing_nullable=True)
    op.alter_column('characters', 'creator_notes',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment="Creator's notes about the character (not sent to LLM)",
               existing_nullable=True)
    op.alter_column('characters', 'system_prompt',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Per-character system prompt override (V2 spec)',
               existing_nullable=True)
    op.alter_column('characters', 'creator',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Creator or author of the character card',
               existing_nullable=True)
    op.alter_column('characters', 'custom_gender',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment="Custom gender value when gender is set to 'others'",
               existing_nullable=True)
    op.alter_column('characters', 'gender',
               existing_type=postgresql.ENUM('male', 'female', 'non_binary', 'others', name='gender'),
               comment=None,
               existing_comment="Character's gender",
               existing_nullable=True)
    op.alter_column('characters', 'tags',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               comment=None,
               existing_comment='Tags for categorizing and filtering characters',
               existing_nullable=True)
    op.alter_column('characters', 'alternate_greetings',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               comment=None,
               existing_comment='Alternative first messages',
               existing_nullable=True)
    op.alter_column('characters', 'post_history_instructions',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Jailbreak/instructions inserted after chat history',
               existing_nullable=True)
    op.alter_column('characters', 'scenario',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Current scenario/situation for RP context',
               existing_nullable=True)
    op.alter_column('characters', 'avatar_thumbnail',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Path to the generated avatar thumbnail image',
               existing_nullable=True)
    op.alter_column('characters', 'avatar',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Path to the original avatar image file',
               existing_nullable=True)
    op.alter_column('characters', 'example_dialogues',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               comment=None,
               existing_comment='List of example exchanges to guide roleplay style',
               existing_nullable=True)
    op.alter_column('characters', 'first_message',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Initial message the character sends when starting a new chat',
               existing_nullable=True)
    op.alter_column('characters', 'personality',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment="Detailed description of the character's traits and behavior",
               existing_nullable=True)
    op.alter_column('characters', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Brief description or tagline for the character',
               existing_nullable=True)
    op.alter_column('characters', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Display name of the character',
               existing_nullable=False)
    # ### end Alembic commands ###
