"""add_species_and_age

Revision ID: fa2d23a42928
Revises: a40885deaf32
Create Date: 2026-07-04 18:25:14.025062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa2d23a42928'
down_revision = 'a40885deaf32'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('species', sa.String(length=100), nullable=True, comment='Species of the character'))
    op.add_column('characters', sa.Column('age', sa.String(length=100), nullable=True, comment='Age of the character'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'age')
    op.drop_column('characters', 'species')
    # ### end Alembic commands ###
