export const CHAT_PLACEHOLDERS = [
  "What says the scroll?",
  "Whisper into the void...",
  "Consult the ancient texts...",
  "Speak your truth, traveler.",
  "Inscribe your words...",
  "The quill awaits...",
  "What knowledge do you seek?",
  "Echoes of the past...",
  "Unravel the mystery...",
  "Cast your voice...",
  "The library listens...",
  "Pen your destiny...",
  "Chronicle your journey...",
  "Reveal your thoughts...",
  "Invoke the arcane...",
  "Summon your words...",
  "By the light of the candle...",
  "Weave your tale...",
  "What wisdom do you offer?",
  "The pages turn...",
];
