"""drop model routing columns

Revision ID: 4e39835a448d
Revises: af42c0655628
Create Date: 2026-07-11 01:45:26.623365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e39835a448d'
down_revision = 'af42c0655628'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_models_routing_provider_id'), table_name='models')
    op.drop_constraint(op.f('models_routing_provider_id_fkey'), 'models', type_='foreignkey')
    op.drop_column('models', 'routing_provider_id')
    op.drop_column('models', 'routing_identifier')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('routing_identifier', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment="Model identifier on the routing provider (e.g. 'deepseek/deepseek-v4' on OpenRouter, 'deepseek-v4-flash' on OpenCode Go)"))
    op.add_column('models', sa.Column('routing_provider_id', sa.VARCHAR(length=12), autoincrement=False, nullable=True, comment='Optional provider to route through instead of the native one (aggregators like OpenRouter/OpenCode); NULL = use provider_id'))
    op.create_foreign_key(op.f('models_routing_provider_id_fkey'), 'models', 'providers', ['routing_provider_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_models_routing_provider_id'), 'models', ['routing_provider_id'], unique=False)
    # ### end Alembic commands ###
