"""provider_type native enum to varchar

Revision ID: a901608705cb
Revises: f41b9d10346a
Create Date: 2026-07-14 04:13:16.253748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a901608705cb'
down_revision = 'f41b9d10346a'
branch_labels = None
depends_on = None

# Hand-written (not autogenerated): the preceding jsonb migration was unapplied
# on the target DB at authoring time, so autogenerate would have conflated the
# two diffs. The Provider model now maps provider_type via a non-native
# Enum(ProviderType, native_enum=False) -> plain VARCHAR(20); this drops the
# PostgreSQL ENUM type so adding a provider type is a code-only change.
_ENUM_NAME = "providertype"
_ENUM_VALUES = (
    "xai",
    "google",
    "openai",
    "anthropic",
    "openrouter",
    "ollama",
    "lmstudio",
    "opencode",
    "opencode_go",
    "custom",
)


def upgrade() -> None:
    # USING casts the enum to its text value so existing rows carry over verbatim.
    op.alter_column(
        "providers",
        "provider_type",
        existing_type=sa.Enum(*_ENUM_VALUES, name=_ENUM_NAME),
        type_=sa.String(length=20),
        existing_nullable=False,
        existing_comment="Classification of the provider (openai, anthropic, etc.)",
        postgresql_using="provider_type::text",
    )
    # The column was the only user of the enum type; drop it now that it's orphaned.
    op.execute(f"DROP TYPE {_ENUM_NAME}")


def downgrade() -> None:
    providertype = sa.Enum(*_ENUM_VALUES, name=_ENUM_NAME)
    providertype.create(op.get_bind(), checkfirst=True)
    op.alter_column(
        "providers",
        "provider_type",
        existing_type=sa.String(length=20),
        type_=providertype,
        existing_nullable=False,
        existing_comment="Classification of the provider (openai, anthropic, etc.)",
        postgresql_using=f"provider_type::{_ENUM_NAME}",
    )
