"""add task_model_id to chats and profiles

Revision ID: d6b575f2458a
Revises: 9991145fdc05
Create Date: 2026-07-08 08:00:15.885964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6b575f2458a'
down_revision = '9991145fdc05'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('task_model_id', sa.String(length=12), nullable=True, comment='Optional cheaper model for auxiliary calls (titles, suggestions); falls back to model_id when unset'))
    op.create_index(op.f('ix_chats_task_model_id'), 'chats', ['task_model_id'], unique=False)
    op.create_foreign_key(None, 'chats', 'models', ['task_model_id'], ['id'], ondelete='SET NULL')
    op.add_column('profiles', sa.Column('task_model_id', sa.String(length=12), nullable=True, comment='Optional cheaper model for auxiliary calls (titles, suggestions); falls back to the chat model when unset'))
    op.create_index(op.f('ix_profiles_task_model_id'), 'profiles', ['task_model_id'], unique=False)
    op.create_foreign_key(None, 'profiles', 'models', ['task_model_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profiles', type_='foreignkey')
    op.drop_index(op.f('ix_profiles_task_model_id'), table_name='profiles')
    op.drop_column('profiles', 'task_model_id')
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.drop_index(op.f('ix_chats_task_model_id'), table_name='chats')
    op.drop_column('chats', 'task_model_id')
    # ### end Alembic commands ###
