"""json to jsonb for model/family/preset/template params

Revision ID: f41b9d10346a
Revises: b180e88fbb19
Create Date: 2026-07-14 02:48:44.727561

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f41b9d10346a'
down_revision = 'b180e88fbb19'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('model_families', 'parameters',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'),
               existing_comment='Schema and default values for supported parameters',
               existing_nullable=False)
    op.alter_column('model_families', 'extra_metadata',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'),
               existing_comment='Additional family-specific technical metadata',
               existing_nullable=True)
    op.alter_column('model_registry', 'parameters',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'),
               existing_comment='Per-model overrides for sampling and generation parameters',
               existing_nullable=False)
    op.alter_column('presets', 'parameters',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'),
               existing_comment='Sampling parameter overrides (temperature, top_p, etc.)',
               existing_nullable=False)
    op.alter_column('prompt_templates', 'component_order',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'),
               existing_comment='Ordered list of component names for prompt construction',
               existing_nullable=False)
    op.alter_column('prompt_templates', 'components_enabled',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'),
               existing_comment='Map of component names to their enabled status',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prompt_templates', 'components_enabled',
               existing_type=sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_comment='Map of component names to their enabled status',
               existing_nullable=False)
    op.alter_column('prompt_templates', 'component_order',
               existing_type=sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_comment='Ordered list of component names for prompt construction',
               existing_nullable=False)
    op.alter_column('presets', 'parameters',
               existing_type=sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_comment='Sampling parameter overrides (temperature, top_p, etc.)',
               existing_nullable=False)
    op.alter_column('model_registry', 'parameters',
               existing_type=sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_comment='Per-model overrides for sampling and generation parameters',
               existing_nullable=False)
    op.alter_column('model_families', 'extra_metadata',
               existing_type=sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_comment='Additional family-specific technical metadata',
               existing_nullable=True)
    op.alter_column('model_families', 'parameters',
               existing_type=sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_comment='Schema and default values for supported parameters',
               existing_nullable=False)
    # ### end Alembic commands ###
