"""add messages chat_id/created_at composite index

Revision ID: fc4ea3fcd13f
Revises: 614c1c3b4343
Create Date: 2026-07-14 00:32:40.895118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc4ea3fcd13f'
down_revision = '614c1c3b4343'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_messages_chat_created', 'messages', ['chat_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_messages_chat_created', table_name='messages')
    # ### end Alembic commands ###
